#!/Users/ryanmoret/.rvm/rubies/ruby-2.6.3/bin/ruby

# frozen_string_literal: true

require 'securerandom'

def key
  @key ||= SecureRandom.uuid
end

def update_secret!
  File.open('./config/secret', 'w') do |file|
    file.write(key)
  end

  puts key
end

update_secret!
